<!DOCTYPE html>
<html>
<head>
    <meta name="description" content="Footer section" />
	<meta name="keywords" content="PHP, MySql" />
	<meta name="author" content="Ju Han Ng"  />

    <script src="lib/jquery/jquery-1.11.0.min.js"></script>
    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
</head>

<body>
    <footer class="bs-docs-footer" style="text-align: center; padding-top: 4vh;">
        <p>Copyright © 2022. All rights reserved.</p>
    </footer>	
</body>
</html>