<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <meta name="description" content="Header section" />
    <meta name="keywords" content="PHP, MySql" />
    <meta name="author" content="Ju Han Ng" />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap4.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css"
    />
    <link rel="stylesheet" type="text/css" href="styles/style.css" />
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a href="./home.php" class="navbar-brand">Home</a>
        <button
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarMenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a display class="nav-link" href="./dashboard.php">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="./enquire.php">Feedback</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="./account_setting.php">Account</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="./logout.php">Logout</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
  </body>
</html>
